### ISSUE TITLE
Launch Checklist

### ISSUE THREAD

**Issue by kytrinyx** [exercism/xlfe#1]
In order to launch we should have:

- [x] LFE as a submodule in [x-api](https://github.com/exercism/x-api/tree/master/problems)
- [x] at least 10 problems
- [x] a "how to get started" topic in the [help repo](https://github.com/exercism/docs) repo (`app/pages/languages/getting-started-with-lfe.md`)
- [x] one to a handful of people willing to check exercism regularly (daily?) for nitpicks to ensure that the track gets off on the right foot
- [x] add track implementors and other designated nitpickers as mentors to the track
- [x] toggle `"active"` to `true` in `config.json`

Some tracks have been more successful than others, and I believe the key features of the successful tracks are:

* Each submission receives feedback quickly, preferably within the first 24 hours.
* The nitpicks do not direct users to do specific things, but rather ask questions challenging people to think about different aspects of their solution, or explore new aspects of the language.

For more about contributing to language tracks on exercism, check out the Problem API Contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md

**Comment by yurrriq** [comment]
- Re: "how to get started"  
  I added a [getting-started-with-lfe.md][1] at yurrriq/docs@2aa00cd95d3bb7f0ce2794ce9529b80b7976f442 and will make a PR when it's ready. @kytrinyx, is that the preferred approach?
- Re: regular nitpickers  
  I'm willing to check exercism daily, and I'm guessing Duncan would be willing with reasonable frequency.
- Re: designated nitpickers  
  I'm not sure I understand this fully, but hopefully Robert can get on board too.
- Re: contributing guide  
  I'll pore over it and make sure to follow the guidelines.

[1]: https://github.com/yurrriq/docs/blob/master/app/pages/languages/getting-started-with-lfe.md

**Comment by kytrinyx** [comment]
Yeah, that's a great approach for the getting started page, thanks!

The designated nitpickers is basically just the regular nitpickers, but they can be given access to nitpick all the problems in the track without having to do the exercises themselves. We don't need them, but it's sometimes nice to have.

If you find anything that is unclear or confusing in the guidelines, let me know!

**Comment by yurrriq** [comment]
Ah, that sounds great actually. We've got a thread on the LFE email list, but @oubiwann and I, at least, are for sure on board for being nitpickers. Thanks for making exercism and for all your help in this!

**Comment by yurrriq** [comment]
Opened exercism/x-api#66 to add LFE as a submodule.

**Comment by yurrriq** [comment]
@kytrinyx, how do we go about adding designated nitpickers? Is it in a config file somewhere?

**Comment by yurrriq** [comment]
I think we're basically ready for the big time here. I can keep adding exercises as I nitpick submissions. I'm excited to see how this track fares in the wild!

**Comment by kytrinyx** [comment]
@yurrriq there's no interface for it yet--if you give me the list of github usernames, I'll make it so.

> I think we're basically ready for the big time here.

w00t! I'll deploy so we can go live.

**Comment by yurrriq** [comment]
Let's do @yurrriq, @oubiwann and @rvirding for now. No promises on Robert but he should be on the list, just in case.

**Comment by yurrriq** [comment]
I'll maybe add a couple more (I think I did a few out of order) and the flip the flag. Thanks for all your help and for exercism in general!

**Comment by kytrinyx** [comment]
Robert's not in the system yet. Remind me if/when he's logged in so that I can add him.

**Comment by yurrriq** [comment]
👍

**Comment by yurrriq** [comment]
This is probably not the best place to ask, but what's the process for adding new exercises, just adding a test and an example?

Someone on the LFE list raised the concern that a lot of the exercises aren't very Erlang-specific and lend themselves more to the C family of languages.

**Comment by kytrinyx** [comment]
Yeah, most of the exercises were made up for the initial ruby track, and probably don't lend themselves to functional languages.

I've put a section about adding new exercises to the contributing guide: https://github.com/exercism/x-api/blob/master/CONTRIBUTING.md#submitting-new-problems -- start there, and feel free to ask questions if anything is unclear.

**Comment by yurrriq** [comment]
Awesome, thank you!

**Comment by yurrriq** [comment]
The flag is flipped.

**Comment by kytrinyx** [comment]
sweet!

**Comment by yurrriq** [comment]
:tada:
